services:
  db:
    image: mongo:7.0.12
    restart: on-failure
    networks:
      - webshop
    environment:
      MONGO_INITDB_ROOT_USERNAME: jesuis
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: webshop
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - db-data:/data/db

  db-interface:
    image: mongo-express:1.0.2
    restart: on-failure
    networks:
      - webshop
    depends_on:
      - db
    links:
      - db
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://jesuis:admin@db:27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH: false
    ports:
      - 8081:8081

  backend:
    build: ./backend/
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - 5000:5000

  frontend:
    build: ./client
    restart: always
    ports:
      - 3000:3000

volumes:
  db-data:
networks:
  webshop:
    driver: bridge
